# Generated by Django 4.2.8 on 2024-02-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_first_name_alter_booking_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(0, '18:00'), (1, '19:00'), (2, '20:00'), (3, '21:00'), (4, '22:00'), (5, '23:00')], default=1),
        ),
    ]
