# Generated by Django 4.2.8 on 2024-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_of_people',
            field=models.IntegerField(choices=[(1, '1 person'), (2, '2 person'), (3, '3 person'), (4, '4 person'), (5, '5 person'), (6, '6 person'), (7, '7 person')], default=0),
        ),
    ]
