# Generated by Django 4.2.8 on 2024-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default='00.00', max_digits=5)),
                ('avability', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=10)),
                ('category', models.CharField(choices=[(0, 'Starter'), (1, 'Main'), (2, 'Dessert')], default=1, max_length=10)),
            ],
        ),
    ]
