# Generated by Django 4.2.8 on 2024-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_category_alter_menu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.IntegerField(choices=[(0, 'Starter'), (1, 'Main'), (2, 'Dessert')], default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
