# Generated by Django 4.2.8 on 2024-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_category_alter_menu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert')], default='Main', max_length=20),
        ),
    ]
