# Generated by Django 4.2.8 on 2024-01-24 15:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
