# Generated by Django 4.2.8 on 2024-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_avability_menu_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('starter', 'starter'), ('main', 'main'), ('dessert', 'dessert')], default='Main', max_length=20),
        ),
    ]
